# Generated by Django 4.1.7 on 2023-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="started_at",
            field=models.DateTimeField(default=models.F("added_at")),
        ),
    ]
