# Generated by Django 4.1.7 on 2023-03-16 03:50

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, storage=pages.models.AbsoluteUrlStorage(), upload_to=""
            ),
        ),
    ]
