# Generated by Django 4.1.6 on 2023-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="citizen_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pan_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
