# Generated by Django 4.1.7 on 2023-04-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_item_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="started_at",
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
