# Generated by Django 4.1.4 on 2023-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_user_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
