# Generated by Django 4.1.4 on 2023-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="citizen_no",
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="pan_no",
            field=models.PositiveIntegerField(default=122),
            preserve_default=False,
        ),
    ]
