# Generated by Django 4.1.7 on 2023-03-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
